services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: App
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - database_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: root
###< doctrine/doctrine-bundle ###

volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
