services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: App
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - database_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: root
  ###< doctrine/doctrine-bundle ###

  ###> doctrine/mongodb-odm-bundle ###
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: App
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongodb_data:/data/db:rw
  ###< doctrine/mongodb-odm-bundle ###

volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
  ###< doctrine/doctrine-bundle ###

  ###> doctrine/mongodb-odm-bundle ###
  mongodb_data:
###< doctrine/mongodb-odm-bundle ###
